<?php
$sqlArray[_DBPREFIX_ . 'threat'] = "
CREATE TABLE IF NOT EXISTS `" . _DBPREFIX_ . 'threat' . "` (
  `id` INT(11) AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `ip` VARCHAR(255) NOT NULL DEFAULT 'UNKNOWN',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
";
